# Site settings
title: Gonebusy
email: admin@gonebusy.com
description: >
  The Only Booking Platform You Need.  Don't build booking from scratch, leverage
  Booking-as-a-Service from GoneBusy.
url: "https://beta.gonebusy.com" # the base hostname & protocol for your site
twitter_username: gonebusy
github_username:  gonebusy

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  parse_block_html: true
sass:
  sass_dir: _sass
gems:
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate
